import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "../styles/globals.css"
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

import "@fortawesome/fontawesome-svg-core/styles";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${exo.className} font-medium`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
